export enum IconNameEnum {
    home = 'home',
    menu = 'menu',
    edit = 'edit',
    email = 'email',
    user = 'user-o',
    lock = 'lock',
    left = 'chevron-left',
    longRight = 'arrowright',
    phone = 'phone',
    trash = 'trash-o',
    heart = 'heart',
    close = 'close',
    info = 'info',
    check = 'check',
    notifyOn = 'bell',
    notifyOff = 'bell-off',
    search = 'search',
    eye = 'eye',
    eyeOff = 'eye-off',
    calendar = 'calendar'
}
